---
title: "Property verification with word repetition detection"
author: "Pierce Edmiston"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: flatly
    toc: true
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(knitr)
library(devtools)
library(dplyr)

opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.path = 'results-figs/'
)

read_chunk("results.R")
read_chunk("subjs.R")
```

```{r, setup}
```

# Subjects

```{r, subjs, fig.width = 4, fig.height = 4}
```

# Overall

```{r, overall-data}
```

## Prompt trials

### Error

```{r, prompt-mod, echo = 1}
```

```{r, prompt-plot}
```

# Version 2

```{r, version2-data}
```

## Prompt trials

### Error

```{r, prompt2-mod, echo = 1}
```

```{r, prompt2-plot}
```

### RT

```{r, prompt2-rt-mod, echo = 1}
```

```{r, prompt2-rt-plot}
```

## Word trials

### Error

```{r, word2-mod, echo = 1}
```

```{r, word2-plot}
```

### RT

```{r, word2-rt-mod, echo = 1}
```

```{r, word2-rt-plot}
```

# Version 3

```{r, version3-data}
```

## Prompt trials

### Error

```{r, prompt3-mod, echo = 1}
```

```{r, prompt3-plot}
```

### RT

```{r, prompt3-rt-mod, echo = 1}
```

```{r, prompt3-rt-plot}
```

## Word trials

### Error

```{r, word3-mod, echo = 1}
```

```{r, word3-plot}
```

### RT

```{r, word3-rt-mod, echo = 1}
```

```{r, word3-rt-plot}
```